### ISSUE TITLE
ISR not in IRAM

### ISSUE THREAD

**Issue by starfish1107** [ThingPulse/esp8266-weather-station-color#102]
have problems with my
older version of weatherstation colour kit  with wemos d1 mini  4M.
clean reinstall arduino ide, compiling and flashing (master, Latest commit 2133809 on 24 Feb) according step by step tutorial
the device is looping / restarting , serial monitor shows:

Connecting to WiFi home1/a1b2c3d4e5
.........Connected...Initializing touch screen...
ISR not in IRAM!

any idea how to get it working?

**Comment by G6EJD** [comment]
I think you may be using ESP8266 core 2.5.0 and in that build ISR’s now have to be located in IRAM, if so try downgrading your IDE to say 2.4.2 either that or add the IRAM prefix / macro to tell the compiler to place the ISR into IRAM.

**Comment by marcelstoer** [comment]
> try downgrading your IDE to say 2.4.2

Not the IDE, but the ESP8266 toolchain i.e. ESP8266 Arduino core as per https://docs.thingpulse.com/guides/wifi-color-display-kit/#install-the-esp8266-toolchain. We will upgrade our code to be compatible with 2.5.x in the following weeks.

**Comment by starfish1107** [comment]
youre right  - now it works again  thanks guys.

**Comment by manj9501** [comment]
There's one more solution, a more correct one.
You can add modify the declaration of Interrupt Service Routine at **line 31** in 
XPT2046_Touchscreen.cpp after installing the XPT2046_Touchscreen library and change it to
`void ICACHE_RAM_ATTR isrPin(void);`
from
`void isrPin(void);`

**Comment by marcelstoer** [comment]
That is an issue with the touch library this app depends upon. Please leave a comment at https://github.com/PaulStoffregen/XPT2046_Touchscreen/pull/24#issuecomment-531621444 asking the maintainer to please release the fix he committed to master back in June.

**Comment by MagnusThome** [comment]
Any updates on this other than downgrading ESP8266 core to before 2.5.0?

**Comment by MagnusThome** [comment]
Manually updated the https://github.com/PaulStoffregen/XPT2046_Touchscreen/ since it isn't updated from the Arduino IDE library manager. Seem to work fine now :-)

**Comment by marcelstoer** [comment]
See my previous comment. If enough people ask for a new release the maintainer may eventually create one.
