### ISSUE TITLE
Replacing the Touch Function with Push Button

### ISSUE THREAD

**Issue by Dancopy** [ThingPulse/esp8266-weather-station-color#103]
Does anyone know how to replace the Touch function with Push Button with resistor PULL_UP in code, maybe on Pin D3?
Cause: My screen (ili9341 2.8") does not have a Touch function.

**Comment by Dancopy** [comment]
Does anyone know how to replace the Touch function with Push Button with resistor PULL_UP in code, maybe on Pin D3?
Cause: My screen (ili9341 2.8") does not have a Touch function.
Thank you

**Comment by plazmax** [comment]
im curious too

**Comment by mazur888** [comment]
Thinking about the same. I think it would be better than touch screen.
