### ISSUE TITLE
Connection screen in loop

### ISSUE THREAD

**Issue by redfirebrooks** [ThingPulse/esp8266-weather-station-color#106]
### Expected behavior

Wifi connect

### Actual behavior

Wifi connect in a loop.
First screen OK, it shows the progress bar but when it reaches the end the screen goes black and the entire process starts again.

### Weather Station Color version

unknown, the screen looks OK

### Hardware

Custom hardware
https://fr.aliexpress.com/item/32651747570.html?spm=a2g0s.9042311.0.0.27426c37CirZg3

Serial monitor output

**Comment by marcelstoer** [comment]
I bet you're seeing "ISR not in IRAM!" when you check the serial console, no?

**Comment by redfirebrooks** [comment]
yep, I managed to socle it lowering the IDE version
