### ISSUE TITLE
MoonAge wrong

### ISSUE THREAD

**Issue by bernemer** [ThingPulse/esp8266-weather-station-color#109]
Hi,
at my installation i habe a wrong MoonAge.
Today at Oct 11 2019 12:35 CEST the Station say we have Fullmoon (Age 14d, Illum 97%) but Fullmoon is at Oct 13 2019 at 23:07CEST.

Time an Date are ok.

Anybody an Idea?

**Comment by G6EJD** [comment]
It’s an approximation

**Comment by bernemer** [comment]
You have the same effect?
2 1/2 days is a lot.

**Comment by bizhostnc** [comment]
Believe this is affected by the channel you choose in weather API. You must choose one that is most suitable to your actual conditions, hence this is why I have a local station, and a WiFi station. Eventually I may try to log the current information to internet, but not now.

**Comment by G6EJD** [comment]
Moon age is usually derived as it is not generally sent in the API, it is possible the calculations are slightly in error.

**Comment by bernemer** [comment]
If i understand the code right, the moonage is bulit from the calculation of illumination .
But the illumination of the Moon is not linear. 
So in the near of full and new moon the moonage is high.

Thanks for the answers

I close the issue with no correction.
