### ISSUE TITLE
Feature Request: Daily Forecast rather than hourly

### ISSUE THREAD

**Issue by tgreening** [ThingPulse/esp8266-weather-station-color#111]
Feature Request not Issue

Is there a way to do a daily forecast rather than hourly/twice a day?  I like to see a daily forecast rather than a point in time.

Thanks for your consideration.

**Comment by marcelstoer** [comment]
There's a discussion about this in the upstream library: https://github.com/ThingPulse/esp8266-weather-station/pull/164
-> closing this here to consolidate discussions
