### ISSUE TITLE
Can't connected wifi

### ISSUE THREAD

**Issue by page4me** [ThingPulse/esp8266-weather-station-color#119]
I can't connect to wifi The settings are correct: ssid and password api key. All time is connected to WIFI "myssid" preloader goes to the end and shows Connected to WIFI "myssid" and so nothing else is displayed all the time. Wifi data entered in the settings and esp8266 file manula connect wifi and the connection does not work. In console i have this : 

`Connecting to WiFi P4 2G/44FCWXRC
.Connected...Initializing touch screen...
ISR not in IRAM!

User exception (panic/abort/assert)
Abort called

>>>stack>>>

ctx: cont
sp: 3ffffed0 end: 3fffffc0 offset: 0000
3ffffed0:  3ffe89ba 00000000 55002e2e 4020c9f1  
3ffffee0:  000000fe 00000000 00000000 00000000  
3ffffef0:  00000000 00000000 00000000 00ff0000  
3fffff00:  5ffffe00 5ffffe00 3ffe89ae 00000000  
3fffff10:  00000002 00000005 3ffe8534 4020b12a  
3fffff20:  40100526 00000000 002e2e2e 4020b13c  
3fffff30:  3ffef71c 00000000 3ffe8534 4020b645  
3fffff40:  00000000 3ffef768 3ffe8f3f 4020970c  
3fffff50:  40209700 3ffef768 3ffe8f3f 3ffef894  
3fffff60:  3fffdad0 000000ff 3ffe8534 4020b6f4  
3fffff70:  3fffdad0 3ffef768 3ffe8534 402056dd  
3fffff80:  3fffdad0 3ffef768 3ffef518 40201d39  
3fffff90:  feefeffe feefeffe feefeffe feefeffe  
3fffffa0:  3fffdad0 00000000 3ffef854 4020ab2c  
3fffffb0:  feefeffe feefeffe 3ffe858c 40100e45  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 3456, room 16 
tail 0
chksum 0x84
csum 0x84
va5432625
~ld
16
`

**Comment by WOnken** [comment]
I am having exact the same issue... And this happened after an update. Not a brand new installation. Before that it was running. My Arduino IDE as well as all libraries are absolutely up to date. There must be an error in the code

**Comment by G6EJD** [comment]
Earlier versions of the IDE allowed an interrupt service routine to not reside in IS RAM, so this is why the issue is occurring, if your downgrade to a an IDE version maybe 2.4.2 it will be OK until the source code is modified to include the IRAM prefixes, actually I thought they had been updated, are you sure you have the latest source code?

**Comment by marcelstoer** [comment]
The issue title is "Can't connected wifi". Yet the console log apparently says

```
Connecting to WiFi P4 2G/44FCWXRC
Connected...
```
So, no, WiFi connection is not an issue.

> actually I thought they had been updated

Yes, they have. If folks bothered to read the documentation linked in the README, particularly https://docs.thingpulse.com/guides/wifi-color-display-kit/#install-libraries, they wouldn't have this issue.
