### ISSUE TITLE
Change WiFi and other settings?

### ISSUE THREAD

**Issue by glen4cindy** [ThingPulse/esp8266-weather-station-color#123]
Is it possible to access a settings page via the IP address of the ThingPulse weather station?

There are settings I would like to change but the IP address is not responding. 

I've tried Telnet and SSH too.

TIA

**Comment by marcelstoer** [comment]
There is no webserver (or any other server socket) running. If you need to change anything in https://github.com/ThingPulse/esp8266-weather-station-color/blob/master/settings.h you need to reflash the device.
