### ISSUE TITLE
Temperature not displayed in "Current Conditions" page

### ISSUE THREAD

**Issue by JMe4801** [ThingPulse/esp8266-weather-station-color#139]
8<------------------------ BUG REPORT -----------------------------------------
Latest version of esp8266-weather-station-color.ino available

in line 503 you have : 

```c++
drawLabelValue(0, "Temperature:", currentWeather.temp + degreeSign);
```

i suggest you replace with : 

```c++
drawLabelValue(0, "Temperature:", String(currentWeather.temp,1) + (degreeSign));
```
Apologies if i do not follow all the rules of githup, first time for me i use it ;-).

Regards.

Jacques

8<------------------------ END BUG REPORT -------------------------------------

**Comment by marcelstoer** [comment]
Thanks, the original code indeed does look oddly wrong. I'll need to test this myself first, though.
