### ISSUE TITLE
Moon phase graphic incorrect

### ISSUE THREAD

**Issue by brianmiller1956** [ThingPulse/esp8266-weather-station-color#143]
The moon phase graphic is incorrect, the text says full moon, I look out of the window and the full moon is present so it does calculate the moon age and illumination correctly but the graphic displayed shows nothing like this, it just shows effectively a letter C which is incorrect, can the graphic be synchronised with the text please. Otherwise a great project.

**Comment by ionut531** [comment]
Yeah, I can confirm too. Even though the settings are correct, the moon phases are wrong. Currently, in my zone, the moon is 0.2 days, but it should be 28 days thus the graphing to be incorrect also.

**Comment by VentoFahrer** [comment]
https://support.thingpulse.com/1297/moon-icon-inverted-showing-black-fixed-esp8266-color-display

See the Last Post

**Comment by marcelstoer** [comment]
There's a potential fix pending in the `fix/moon` branch at https://github.com/ThingPulse/esp8266-weather-station-color/blob/fix/moon/esp8266-weather-station-color.ino. Soon to be merged.

**Comment by brianmiller1956** [comment]
I have downloaded this update and it does look much better, the graphic matches what I see out of the window, many thanks for all the hard work, I appreciate the work involved.

**Comment by marcelstoer** [comment]
Thanks for the feedback, good to know. Later we might even be able to rotate the font character dynamically to give a more realistic representation of the moon.

**Comment by brianmiller1956** [comment]
That sounds great, the icon really could do with a little more detail rather than just a flat disk.
