### ISSUE TITLE
 esp8266-weather-station-color - problem with 2,4" ST7789V LCD Display

### ISSUE THREAD

**Issue by kleryk02** [ThingPulse/esp8266-weather-station-color#152]
Hi Marcel,

I think that you make a great job at this project.
I have got a one questions. You can help me with make a new code in this project for 2,4 "ST7789V LCD Display?
A lot of people have problems with this driver because it uses the display with the ST7789V driver, and the project is based on libraries for ILI9341. Thanks a lot.

**Comment by marcelstoer** [comment]
We only write and support software for free for the hardware we have in our shop, sorry. However, it's probably not too difficult to use the Adafruit driver https://github.com/adafruit/Adafruit-ST7735-Library.
