### ISSUE TITLE
SunMoonCalc implementation seems to be omitted

### ISSUE THREAD

**Issue by suculent** [ThingPulse/esp8266-weather-station-color#161]
Current source does not build since there was a change from Astronomy to SunMoonCalc (which is yet not added to the repo).

### Test code

The default sketch is just not buildable.

### Weather Station Color version

master, last commit

### Hardware

ThingPulse Weather Station Color kit

**Comment by marcelstoer** [comment]
Not reproducible, SunMoonCalc has been part of https://github.com/ThingPulse/esp8266-weather-station (a dependency fo this project) for 4+ years.
