### ISSUE TITLE
Calibrate touch screen issue 

### ISSUE THREAD

**Issue by Temneanu80** [ThingPulse/esp8266-weather-station-color#166]
Does anyone know why i can pass the screen calibration
The touch screen it's working but when i press the white dot nothing happened
Thank you 
![16851874270959006973115454641987](https://github.com/ThingPulse/esp8266-weather-station-color/assets/70949400/41ec3cb6-dc05-42e2-bad6-c79b008f3706)

**Comment by TiVoHomeUser** [comment]
Does not look like it is from this kit. How is it wired? What display?

**Comment by G6EJD** [comment]
It doesn’t work because most of those displays don’t have a touch controller or if it does, then historically they don’t work due to faulty or fake devices. It’s what happens when you buy cheap devices!
