### ISSUE TITLE
Please amend square pin on Color Display Connector,, U2, to have the Square land at Vcc

### ISSUE THREAD

**Issue by herrold** [ThingPulse/esp8266-weather-station-color#32]
The present revision of the IL9341 connector (U2) has the square Pin 1 as a meaningless Tirq, for its mating board -- the mating board has the Square Pin 1 for Vcc, which is not unexpected

Please conform the Color Display Connector card to match the square pin1 of the IL9341 (the layout and silkscreen of which I assume is out of your control)

**Comment by squix78** [comment]
Hi @herrold 
Sorry for the long response time. Can you explain a bit more how we should change the board? A photo with some annotations might help. Thank you.

**Comment by herrold** [comment]
sure -- I'll bring the unit in and do so overnight
