### ISSUE TITLE
Change language to German

### ISSUE THREAD

**Issue by djuscha** [ThingPulse/esp8266-weather-station-color#36]
Hab almost everything in German converted, only Forecast window shows me weather still in English .We are days in German. And in the main window above the date is in English how can I change that.
http://api.wunderground.com/api/apikey/forecast10day/lang:DL/q/Baunatal.jsonShows me the weather in German.
What am I doing wrong?
Everything else is in German and the comments I have also translated

**Comment by Luc3as** [comment]
Hello, 
there is possibility now to translate the ui to other languages, see 
https://github.com/squix78/esp8266-weather-station-color/pull/43

**Comment by djuscha** [comment]
Have tried still language_DE.h and language_RU.h to reiposten does not know whether you can embed that.

**Comment by Luc3as** [comment]
If you do have translated the original file and saved it as language_de.h
the include definition is is main code file. Src/weather station color. Ino

Dňa 19. 9. 2017 8:31 odpoludnia používateľ "djuscha" <
notifications@github.com> napísal:

**Comment by djuscha** [comment]
eather-station-color.ino:55:25: fatal error: language_EN.h: No such file or directory

 #include <language_EN.h>

                         ^

compilation terminated.

**Comment by djuscha** [comment]
have changed and now works switch between windows no more. even if I leave in English there is only one window.

**Comment by Luc3as** [comment]
oh, I see, please uncomment line 222 //screen = (screen + 1) % screenCount;  in esp8266-weather-station-color.ino   I had problems with touchscreeen so I disabled rotating by touch and forget to put it back.

**Comment by djuscha** [comment]
yes now But it is only komentare translated that I had already sketch translated directly. Im sketch also const string WUNDERGRROUND_LANGUAGE = "DL";
const String WUNDERGROUND_COUNTRY = "DE"; and still as I have written stands up in the first window day in English and weather display in the forestcast is still in English.also as before :(

**Comment by Luc3as** [comment]
hmmm I think there is some strings hard coded in weather station library
which is used to download forecasts

2017-09-20 12:05 GMT+02:00 djuscha <notifications@github.com>:

**Comment by djuscha** [comment]
Russian is not at all :(

**Comment by Luc3as** [comment]
can you post photo of what is displaying wrong on display ?

2017-09-20 13:02 GMT+02:00 djuscha <notifications@github.com>:

**Comment by djuscha** [comment]
https://github.com/djuscha/esp8266-weather-station-color
here are the pictures. De for German and RU for Cyril

**Comment by Luc3as** [comment]
Okay, so the main problem here is the builtin font cannot show russian
characters at all, because there is just basic set of characters. solution
to this would be adding your russian charracters to the translit function,
which would change those charracters for latin characters. you can find
inspiration for characters to put to array here
https://stackoverflow.com/questions/7461406/cyrillic-transliteration-in-php

just keep in mind, after adding characters to the array, String lat_up[]
and so on, count elements in array and put that number to  for (int i = 0;
i < 11 ; i++) {

2017-09-20 14:47 GMT+02:00 djuscha <notifications@github.com>:

**Comment by djuscha** [comment]
this is too difficult for me with russian :( .. the good I am not in the program
and what is with German? there is not translated everything.

**Comment by Luc3as** [comment]
I updated the code for you, please try if it translating russian
charracters now, with german I think I cannot change it because it is hard
coded to library which we are using

2017-09-20 20:23 GMT+02:00 djuscha <notifications@github.com>:

**Comment by djuscha** [comment]
have just tried with russian ... it is just like before, no change to see :(

**Comment by Luc3as** [comment]
Sorry my fault. I forgot to update number in for loop statement

Dňa 20. 9. 2017 9:34 odpoludnia používateľ "djuscha" <
notifications@github.com> napísal:

**Comment by herrold** [comment]
@Luc3as said:
--- Just keep in mind, after adding characters to the array, String lat_up[] and so on, count elements in array and put that number to for (int i = 0; i < 11 ; i++)

computers are much more accurate than humans in counting -- is there not a 'length of' macro which can do this automatically at compile time?

**Comment by herrold** [comment]
... sorry about all the markup changes -- I normally use another variant

**Comment by Luc3as** [comment]
Yup I'm sure it is. Honestly I tried to get length somehow and it was not
working, more specifically it was crashing esp, so I put the number of
elements hard here. But it was just quick fix and I kept it this way. I
will look at it and do it as you suggest.

Dňa 20. 9. 2017 10:41 odpoludnia používateľ "Russ Herrold" <
notifications@github.com> napísal:

**Comment by djuscha** [comment]
update number in for loop Statement  still not changed?

**Comment by Luc3as** [comment]
Hello, I updated code to automatically count number of ellements in array, you can try

**Comment by djuscha** [comment]
now what is displayed, but are russian words in translit, russian words with latin letters :(

**Comment by Luc3as** [comment]
Correct, this is max I can do without knowing how to generate font files to
progmem.

Dňa 21. 9. 2017 11:46 dopoludnia používateľ "djuscha" <
notifications@github.com> napísal:

**Comment by djuscha** [comment]
oh so all clear, thanks for your work !!
