### ISSUE TITLE
wake up from sleep

### ISSUE THREAD

**Issue by starfish1107** [ThingPulse/esp8266-weather-station-color#47]
how to wake up from sleep. Actually only reset works - by intention?  Tapping on display would be nice.

**Comment by G6EJD** [comment]
Have you linked GPIO16 to RST? IF the ESP8266 is placed in sleep mode only a Reset or timer time-out and transition on RST will wake it up.

Tapping on the display could work if the touch sensor had an interrupt capability and a dedicated pin that could be OR'd to the RST so either time-out or touch would wake the ESP.
