### ISSUE TITLE
Carousel not smooth

### ISSUE THREAD

**Issue by dkotte** [ThingPulse/esp8266-weather-station-color#48]
First i build weather station with with small OLED display. Nice.
Now i build weather-station color. Great. Thanks a lot!
But the carousel from weatherstation color change pages with jumps and is choppy while at the small device it runs very smooth. That gives problems with the WAF :-) 
Is there an error i made or an option to optimize the page-change?
Where i can set the time used for page change?

**Comment by rickylee64** [comment]
same issue for me. the display cycles through 5 pages way too fast, about 5 pages in 2 or 3 seconds. a touch screen issue maybe?

**Comment by marcelstoer** [comment]
This is actually a dup of #22. @stamatoulis thanks for the workaround.

**Comment by dkotte** [comment]
Hi marcelstoer,
the problem here is NOT the cycling from one infoscreen to the other because the missing touch chip/connection. (a similar workaround for this problem i build too)
My problem here is the display quality within the carussel function.
PS: auf deutsch könnte ich das Problem genauer beschreiben.

**Comment by MarioP73** [comment]
Schreib mal auf deutsch
