### ISSUE TITLE
2.2tft/No touch

### ISSUE THREAD

**Issue by dwhacks** [ThingPulse/esp8266-weather-station-color#52]
I've been using your old .ino on a 2.2tft for a year at least now and its been great. I noticed all these new updates, and in the new settings there is "define HAVE_TOUCHPAD". Does this mean we can use it without a touchpad? So far it seems to just cycle through the screens.

Also, I had to remove the D from the pin designations in the settings file for it to compile.

**Comment by marcelstoer** [comment]
Dup of #48
