### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by JorikWit** [ThingPulse/esp8266-weather-station-color#54]
Any plans to tweak the code for the esp32?

**Comment by dronecz** [comment]
Maybe this wil help: https://github.com/squix78/esp8266-weather-station/issues/71

**Comment by JorikWit** [comment]
Thanks for your comment. But I have already used a other library. https://github.com/G6EJD/ESP32-Weather-Station-using-1.3-OLED

**Comment by blotfi** [comment]
Is there a planned port to ESP32 or not ?

**Comment by marcelstoer** [comment]
There's a more material conversation in #71 -> closing this one
