### ISSUE TITLE
No information

### ISSUE THREAD

**Issue by ionut777** [ThingPulse/esp8266-weather-station-color#56]
Hello Guys,
I made the project with ESP8266 (NodeMcu) and 2.4 inch display but I don't have any information regarding the weather forecast on the display.
I change the setting.h, API key, 
but nothing.
Anybody a solution? 
Thank you

![img_20180214_154256](https://user-images.githubusercontent.com/36478339/36207401-7d38772a-119e-11e8-8ac4-c8c8565f8f01.jpg)

**Comment by G6EJD** [comment]
Looks like your API key needs to be renewed have you tried it in your web browser command line go to WU and thief examples and then replace their key with yours

**Comment by ionut777** [comment]
Hello G6EJD,
Seems to works the API Key
http://api.wunderground.com/api/af64c0f78292aadd/conditions/q/RO/Oradea.json

**Comment by ionut777** [comment]
Not it's ok
in the setting.h was <API KEI> and i delete"<>" and now it's working
Thank you!

**Comment by G6EJD** [comment]
Ok good, so now you need to check your country code and location are supported by WU, are you using the same codes? If so it is difficult to see what else is wrong with this mature code that works for so many people.

**Comment by G6EJD** [comment]
Good I would clear your API key from this correspondence though

**Comment by marcelstoer** [comment]
The key posted above is now invalid which is good.
