### ISSUE TITLE
Screen Rotation

### ISSUE THREAD

**Issue by 556duckvader** [ThingPulse/esp8266-weather-station-color#58]
How do you go about rotating the screen to landscape?  I have looked and I am not really seeing where to configure that.

**Comment by G6EJD** [comment]
Well the simple adjustment would be to swap screen height and width, but it's not as simple as that as the minigfx library has no screen rotate and the whole project has been designed (x,y layouts) to be 240x320. You could write a function to rotate the screen and go through the whole programme to adjust all the x and y offset values for landscape.

Has anyone done this?

**Comment by pilnikov** [comment]
![image](https://user-images.githubusercontent.com/25922873/37442641-4d12e110-2829-11e8-9453-8259e0237af7.png)

**Comment by marcelstoer** [comment]
@G6EJD actually answered this -> closing
