### ISSUE TITLE
compile for ESP32 Lolin32 lite

### ISSUE THREAD

**Issue by blotfi** [ThingPulse/esp8266-weather-station-color#62]
Hi
I am trying to compile this prg to ESP32 Lolin32 lite
I first tried to compile for Wemos lite (ESP8266) and it was fine. So I know I have all the libraries installed correctly.
Then I started with a Lolin32 lite target:
I modified to
#include <ESPWiFi.h>
added
#include "SPIFFS.h" in TouchControllerWS.cpp

It complained about
ESP.function_of_sleep_and_so...
So I commented them

also commented  ADC_MODE(ADC_VCC);

After that it compiles well.
--------
The questions now:

it seems that the screen consumes lot of power (because of the BL ?) (3.3V is 2.8V !)

The screens toggles very fast (like 0.3 s per screen), where can we change the period in the carousel config?

Am I using a H/W SPI ? if not how can I fix this

What about the sleep mode and ESP.xxxx related functions, is there a special syntax for ESP32 ?

also, how can I get rid off DST, there is no DST in my country.

#define UTC_OFFSET + 1
struct dstRule StartRule = {"CEST", Last, Sun, Mar, 2, 3600}; // Central European Summer Time = UTC/GMT +2 hours
struct dstRule EndRule = {"CET", Last, Sun, Oct, 2, 0};       // Central European Time = UTC/GMT +1 hour

thanks

**Comment by blotfi** [comment]
I see that it is because I didn't connected the touch part that the carousel toggles the screen very fast!

**Comment by G6EJD** [comment]
DST change 3600 to 0 then time won’t is +1 hr in secs.

**Comment by blotfi** [comment]
I will delete the use of the touch screen since the ESP32 has a touch interface ;-)
