### ISSUE TITLE
Make full translation easier

### ISSUE THREAD

**Issue by tigers75** [ThingPulse/esp8266-weather-station-color#69]
8<------------------------ FEATURE REQUEST ------------------------------------
### Justification
I'd like to translate the whole interface to Italian (or any language): setting the proper language code in the settings for WU does the trick for 90% of the interface, but some stings remain in english and others are buried deep in one of the libraries used and not easy to find.

### Workarounds
I can see that some of the strings are in the main code in esp8266-weather-station-color.ino, and they can be edited in place, but it'd be much better to have them collected in the settings.h file.

I'haven't found yet month/ weekday names that must be in some library. I have a custom version of the Time library from the Arduino Core where I changed month and weekdays long and short, but it clearly picks the names from somewhere else.

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by G6EJD** [comment]
The month and day text comes from WU, if you select IT for your language, does it not give you month / day in Italian, I thought WU then output in your language, maybe not.

**Comment by tigers75** [comment]
It's only partially true: on top of the clock there're still english short text (see image). Also in the bottom part "Sun" and "Moon" are in english (but they're in the main 
![2018-05-21 13 05 17](https://user-images.githubusercontent.com/37505492/40359246-4d079d22-5dc2-11e8-925e-42c064c6cc01.jpg)
code and easy to replace).

**Comment by pilnikov** [comment]
https://github.com/pilnikov/Color-Weather-Station/blob/master/resources/pic1.jpg
all string on russian languange

**Comment by marcelstoer** [comment]
Dup of #34
