### ISSUE TITLE
Weather Underground Alternative?

### ISSUE THREAD

**Issue by craigistired** [ThingPulse/esp8266-weather-station-color#71]
8<------------------------ FEATURE REQUEST ------------------------------------
### Justification
API keys are no longer being offered. 
https://apicommunity.wunderground.com/weatherapi/topics/weather-underground-api-changes

### Workarounds
I currently hace no workarounds.
8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by marcelstoer** [comment]
Yep, stay tuned, see https://thingpulse.com/weather-underground-no-longer-providing-free-api-keys/
