### ISSUE TITLE
Name of days and forecast detail disappear. 

### ISSUE THREAD

**Issue by tigers75** [ThingPulse/esp8266-weather-station-color#72]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
There should be day names over low|high temperature, and a detailed description in the "weekly" forecast pages.

### Actual behavior
They disappear randomly: sometimes it runs for days without a issue, sometimes they disappear after a few hours. Restarting the station always fix it.
For what I have seen once they are gone they don't come back (I waited for a forecast update to happpen). The WiFi it's OK, and so are the current weather data and the icons and min|max temperatures. It may be an an error on WU side, but shouldn't fix itself in the long run on that case? Maybe an error on parsing?
Also if the problem is on WU why it fixes on a simple reset? It should read the same "wrong" data and still not display correctly.

### Test code
I'm using the main code with only a sligth modification to the drawastronomy to display reading from my energy meter, that come via an UDP broadcast message on my local network.
I also noticed this beaviour once with the untouched code.

### Weather Station Color version
I'm'using the master branch in the latest versione currently available.

### Hardware
The code runs on a NodeMCU 1.0 v2 (Lolin) with an ILI9341 identical to the one of the original kit.

![2018-05-26 07 43 00](https://user-images.githubusercontent.com/37505492/40573628-7053267a-60c4-11e8-8e67-511b77c1f77f.jpg)

![2018-05-26 07 42 52](https://user-images.githubusercontent.com/37505492/40573626-6fcee2ca-60c4-11e8-9b17-cc4ac19aa3e8.jpg)

8<------------------------ END BUG REPORT -------------------------------------

**Comment by tigers75** [comment]
OK, I digged deeper in the weekend and it seems in fact that the missing data is not definitely gone, sometimes it shows up again after an update.
Looks like the problem is in the weather underground part: if some data is "missing" in parsing the WU response the display shows empty places. I think it should be modified to retry in a short while and in the meantime keep showing the old values when something goes wrong.

**Comment by G6EJD** [comment]
I’ve been doing that in my weather station implementations and leave all the display data as last received until a valid new set of new data is received, although I think it makes for a better solution it’s often difficult to know if there’s been an update or not, so I’m divided and missing data on screen is a useful indicator of a problem. Now I’ve moved over to Openweathermap servers I’ve noticed they are more consistent and reliable.

**Comment by tigers75** [comment]
Yes, I just noticed the change and I'm going to try it. Can you post the code you modified and maybe send a PR? I think it should just be there. Maybe if after some retries something is still wrong put a "not updated" message on screen.

**Comment by marcelstoer** [comment]
[Weather Underground closed their existing API](https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api) for non-paying customers on 2018-12-31. After [they stopped issuing free API keys](https://thingpulse.com/hello-openweathermap-bye-bye-wunderground/) for low-volume personal use in May we migrated to OpenWeatherMap and [deprecated all WU code](https://github.com/ThingPulse/esp8266-weather-station#deprecation-notes) in this library.

We are now closing all WU-related issues and PRs.
