### ISSUE TITLE
Missing OpenWeatherMap<Current | Forecast>.h files

### ISSUE THREAD

**Issue by cmmh** [ThingPulse/esp8266-weather-station-color#75]
### Expected behavior
Successful compile

### Actual behavior
Missing include files for new OpenWeatherMap usage

### Test code
Perhaps still being written, but include files for OpenWeatherMap are missing.

### Weather Station Color version
Only appears to be a master branch here on github

### Hardware
Factory fresh ThingPulse kit.

**Comment by marcelstoer** [comment]
Dup of #74.
