### ISSUE TITLE
No data from Open Weather shown

### ISSUE THREAD

**Issue by ht81** [ThingPulse/esp8266-weather-station-color#76]
I have succesfully created a API for Open Weather and copie it via copy & paste into settings.h. Also i have edit the "location". My problem ist i can´t see anything on the screen from open weather. 
It shown only a cloud with questionmark. Time / Touchscreen is working correct.on slidung forcast at page 1, the time on the little forcasts ist 2:00.... and nothing more infos about rain, temp etc....

what do i wrong?

**Comment by tedbmoss** [comment]
Same problem

**Comment by tedbmoss** [comment]
Using your hardware

**Comment by marcelstoer** [comment]
If you don't provide the serial console output there's no way for us to assess this support case.

**Comment by tedbmoss** [comment]
error is city not found, I was trying Peoria,AZ I tried Phoenix,US and it worked.

**Comment by tedbmoss** [comment]
I just used the city code.

**Comment by marcelstoer** [comment]
Yep, this issue inspired #81 and ultimately lead to ThingPulse/esp8266-weather-station#122 (using OWM location id will become new default).
