### ISSUE TITLE
OpenWeatherMap includes missing

### ISSUE THREAD

**Issue by al-ang** [ThingPulse/esp8266-weather-station-color#77]
The sketch has the following includes
  #include <OpenWeatherMapCurrent.h> 
  #include <OpenWeatherMapForecast.h> 

but the files don't seem to be in the GitHub repository.  Will you publish them soon, or am I making an obvious error and don't see something that's right in front of my eyes?

**Comment by G6EJD** [comment]
You need to install •ESP8266 Weather Station using Sketch, Manage search for •ESP8266 Weather Station install it, the libraries are in that repository. Or go to the •ESP8266 Weather Station repository on Github and have a look in the SRC folder there.

**Comment by al-ang** [comment]
ah ... got it.  thank you!

**Comment by marcelstoer** [comment]
The guide for customers - and everybody else - is linked on the README: https://github.com/ThingPulse/esp8266-weather-station-color#step-by-step-tutorial
