### ISSUE TITLE
Change from OWM city,country to ID

### ISSUE THREAD

**Issue by marcelstoer** [ThingPulse/esp8266-weather-station-color#81]
The client should be changed to accept location ID rather than `city,country` to avoid ambiguety as [recommended by OWM in their docs](https://openweathermap.org/current#cityid).
Link to https://openweathermap.org/city for `city,country` → ID resolution and adjust comment in file accordingly.

See https://github.com/ThingPulse/esp8266-weather-station-color/blob/master/settings.h#L48 et.al.

**Comment by tedbmoss** [comment]
thanks for help on this, mine works
