### ISSUE TITLE
small issue with font displaying an A with the degree symbol.

### ISSUE THREAD

**Issue by tedbmoss** [ThingPulse/esp8266-weather-station-color#82]
I don't know how to say anything more about this, I just took the symbol out until I can figure it out.
The symbol is an A with a carat instead of a degree symbol.

**Comment by marcelstoer** [comment]
Dup of ThingPulse/esp8266-weather-station#123 but more appropriate here.

**Comment by tedbmoss** [comment]
thanks again for the help with this, it works as intended.
