### ISSUE TITLE
Weater Station with different Display

### ISSUE THREAD

**Issue by hardtacker** [ThingPulse/esp8266-weather-station-color#86]
Hello,

I am very interested at this project.

Currently I have the following display at home and I would like to use this display for the project.

can you help me to get the right connection between NodeMCU V3 ESP8266 ESP12 and the display?

Also the changes in the Code?

Attached the Link to the Display for the pinout.

https://www.amazon.de/Ils-Shield-ILI9341-Display-Arduino/dp/B0769FT28W/ref=sr_1_cc_1?s=aps&ie=UTF8&qid=1533626652&sr=1-1-catcorr&keywords=2.4%E2%80%B3+ILI9341+Color+Display+TFT

Thx

Hardtacker

**Comment by G6EJD** [comment]
Decide which pins to use for the CD etc then
Write a short programme that prints out which pins are used for the SPI bus e.g.
Serial.println(MOSI);
Serial.println(SCK);
Serial.println(SS);

Connect the display accordingly.
SS to CS
CD Pin to CD
MOSI to MOSI
SCK to SCK
and so-on
