### ISSUE TITLE
Feature request: DHT sensor for indoor temperature

### ISSUE THREAD

**Issue by mario-g0** [ThingPulse/esp8266-weather-station-color#88]
### Justification
Since it was added for the "non color" version, it would be nice to have the possibility of adding a DHT sensor and have the station display indoor temperature too.

### Workarounds
Looks like there are no more pin available on the wemos d1, so it would be nice to switch to a nodemcu or similar which already have pins, thus not requiring soldering and allowing expansion

**Comment by marcelstoer** [comment]
There's some discussion about available pins at https://support.thingpulse.com/502/which-pins-can-use-projects-with-your-weather-station-setup. Although the request is comprehensible I don't see ourselves changing the hardware this software was built for any time soon. So, the best way forward for you would be to fork this repository and start tinkering.
