### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by MrBean14** [ThingPulse/esp8266-weather-station-color#90]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
Compiling

### Actual behavior
Compiling with error

`Arduino: 1.8.6 (Windows 7), Board:"Adafruit Feather HUZZAH ESP8266, 80 MHz, Flash, 4M (3M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

sketch\esp8266-weather-station-color.ino.cpp.o: In function `updateData()':

C:\Users\MrBean\Documents\Arduino\esp8266-weather-station-color/esp8266-weather-station-color.ino:308: undefined reference to `TouchControllerWS::loadCalibration()'

C:\Users\MrBean\Documents\Arduino\esp8266-weather-station-color/esp8266-weather-station-color.ino:308: undefined reference to `TouchControllerWS::startCalibration(void (**)(short, short))'

C:\Users\MrBean\Documents\Arduino\esp8266-weather-station-color/esp8266-weather-station-color.ino:309: undefined reference to `TouchControllerWS::continueCalibration()'

C:\Users\MrBean\Documents\Arduino\esp8266-weather-station-color/esp8266-weather-station-color.ino:309: undefined reference to `TouchControllerWS::isCalibrationFinished()'

sketch\esp8266-weather-station-color.ino.cpp.o: In function `OpenWeatherMapForecast::setAllowedHours(unsigned char*, unsigned char)':

C:\Users\MrBean\Documents\Arduino\libraries\ESP8266_Weather_Station\src/OpenWeatherMapForecast.h:100: undefined reference to `TouchControllerWS::saveCalibration()'

sketch\esp8266-weather-station-color.ino.cpp.o: In function `setup':

C:\Users\MrBean\Documents\Arduino\esp8266-weather-station-color/esp8266-weather-station-color.ino:317: undefined reference to `TouchControllerWS::loadCalibration()'

C:\Users\MrBean\Documents\Arduino\esp8266-weather-station-color/esp8266-weather-station-color.ino:319: undefined reference to `TouchControllerWS::startCalibration(void (**)(short, short))'

C:\Users\MrBean\Documents\Arduino\esp8266-weather-station-color/esp8266-weather-station-color.ino:319: undefined reference to `TouchControllerWS::continueCalibration()'

C:\Users\MrBean\Documents\Arduino\esp8266-weather-station-color/esp8266-weather-station-color.ino:320: undefined reference to `TouchControllerWS::isCalibrationFinished()'

C:\Users\MrBean\Documents\Arduino\esp8266-weather-station-color/esp8266-weather-station-color.ino:320: undefined reference to `TouchControllerWS::saveCalibration()'

sketch\esp8266-weather-station-color.ino.cpp.o: In function `drawAstronomy()':

C:\Users\MrBean\Documents\Arduino\esp8266-weather-station-color/esp8266-weather-station-color.ino:640: undefined reference to `TouchControllerWS::isTouched(short)'

C:\Users\MrBean\Documents\Arduino\esp8266-weather-station-color/esp8266-weather-station-color.ino:462: undefined reference to `TouchControllerWS::getPoint()'

C:\Users\MrBean\Documents\Arduino\esp8266-weather-station-color/esp8266-weather-station-color.ino:464: undefined reference to `TouchControllerWS::isTouched(short)'

C:\Users\MrBean\Documents\Arduino\esp8266-weather-station-color/esp8266-weather-station-color.ino:464: undefined reference to `TouchControllerWS::getPoint()'

sketch\esp8266-weather-station-color.ino.cpp.o:(.text.startup._GLOBAL__sub_I_OPEN_WEATHER_MAP_APP_ID+0x108): undefined reference to `TouchControllerWS::TouchControllerWS(XPT2046_Touchscreen*)'

sketch\esp8266-weather-station-color.ino.cpp.o: In function `__static_initialization_and_destruction_0':

sketch/settings.h:63: undefined reference to `TouchControllerWS::TouchControllerWS(XPT2046_Touchscreen*)'

collect2.exe: error: ld returned 1 exit status

exit status 1
Fout bij het compileren voor board Adafruit Feather HUZZAH ESP8266
`

### Test code
https://learn.adafruit.com/wifi-weather-station-with-tft-display?view=all

Code : [https://github.com/adafruit/esp8266-weather-station-color/archive/master.zip](url)

### Weather Station Color version
?

### Hardware

TFT FeatherWing - 2.4' 320x240 Touchscreen For All Feathers
Assembled Adafruit Feather HUZZAH with ESP8266 WiFi With Headers
8<------------------------ END BUG REPORT -------------------------------------

**Comment by marcelstoer** [comment]
This is neither our tutorial nor our (current) code. Please file an issue with Adafruit or follow https://docs.thingpulse.com/guides/wifi-color-display-kit/. I have no idea though (and no way to test) if our current code works on their hardware.
