### ISSUE TITLE
Problem Ili9341 with Touch

### ISSUE THREAD

**Issue by ar84** [ThingPulse/esp8266-weather-station-color#93]
Hello everybody

I have the problem that the Ili9341 with touch does not work.
Everything else works so far without problems.

I have the whole set up instructions and also a Ili9341 with touch function. After the restart it loads everything without problems. The touch reacts but you only see 4x on the flashing of the NODEMCU. Thereafter, the NODEMCU will no longer respond to any touch.

The sketch is original as stated on the page

---------------------------------------------------------------------------------------------------------

Hello everybody
I played around with the code but no improvement. Now the original code is in it again.
The touch display reacts to touch but nothing happens. Actually, the code should switch through the individual windows, or did I misunderstand that?

Thank you

Greeting

**Comment by G6EJD** [comment]
There are many ili9341 displays with fake or faulty touch modules, are you sure your display is a known good one? You will find many reports of faulty touch operation across many forums as a result of these fake chips.
